# Numpy

## NumPy stands for Numerical Python. It is one of the most important libraries in Python used for scientific computing, data analysis, and machine learning. Almost every data science, AI, or machine learning project uses NumPy because it provides fast mathematical operations on arrays and matrices.

## 1. What is NumPy?

### NumPy is a Python library used for:

### Handling large numerical data

### Performing mathematical and statistical operations

### Working with multi-dimensional arrays

### Performing linear algebra and matrix operations

### It is much faster than normal Python lists because it is implemented in C language internally.

## 2. Why NumPy is Used

### Normal Python lists have some limitations:

### Slow for large data

### Cannot perform vector operations easily

### Cannot handle large mathematical computations efficiently

### NumPy solves these problems.

## Advantages

### Faster calculations

### Less memory usage

### Supports multidimensional arrays

### Built-in mathematical functions

### Used in Data Science, AI, ML, Deep Learning

In [2]:
import numpy as np
print("numpy imported")

numpy imported


In [47]:
l = [1,2,3,4,5,6,7]

In [48]:
a = np.array(l)

In [49]:
type(a)

numpy.ndarray

In [17]:
a2 = np.array([1,2,3,4,5])
print(a2)

[1 2 3 4 5]


In [18]:
a3 = np.array([1,2.00,"Raj",4])
print(a3)

['1' '2.0' 'Raj' '4']


In [19]:
a4 = np.arange(5)
print(a4)

[0 1 2 3 4]


In [32]:
a5 = np.arange(-5,-1,1)
print(a5)

[-5 -4 -3 -2]


In [25]:
a6 = np.arange(1,5,2)
print(a6)

[1 3]


In [26]:
a7 = np.arange('a','z')
print(a7)

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [34]:
a.ndim

1

In [35]:
a.shape

(4,)

In [36]:
a.size

4

In [40]:
d2_1 = np.arange(1,13).reshape(2,6)
print(d2_1.ndim)
print(d2_1.size)
print(d2_1.shape)

2
12
(2, 6)


In [43]:
d2_2 = np.arange(1,65).reshape(2,32)
print(d2_2.size)
print(d2_2.shape)

64
(2, 32)


In [45]:
d2_3 = d2_2.reshape(32,2)
print(d2_3.size)
print(d2_3.shape)

64
(32, 2)


In [51]:
d3_1 = np.arange(1,65).reshape(4,4,4)
print(d3_1.ndim)
print(d3_1.shape)
print(d3_1.size)
print(d3_1.dtype)
print(d3_1)

3
(4, 4, 4)
64
int64
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]


In [52]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
a[4]

np.int64(5)

In [56]:
a[4:6]

array([5, 6])

In [57]:
a[2:5]

array([3, 4, 5])

In [58]:
d2_1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [60]:
d2_1[0][1]

np.int64(2)

In [61]:
d2_1[0,1]

np.int64(2)

In [62]:
d2_1[1,1:4]

array([ 8,  9, 10])

In [63]:
d2_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64]])

In [91]:
print(d2_2[0][3],d2_2[0][15])
print(d2_2[0][18],d2_2[1][2],d2_2[1][18])
print(d2_2[1][20],d2_2[1][30])
print(d2_2[1][7],d2_2[1][9])
print(d2_2[0][0],d2_2[1][31])
print(d2_2[1][3],d2_2[1][21])

4 16
19 35 51
53 63
40 42
1 64
36 54


In [97]:
print(d2_2[0,[3,15]])

[ 4 16]


In [98]:
d2_4 = d2_2.reshape(4,16)
print(d2_4)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]]


In [99]:
print(d2_4[[0,1,2,3],[0,1,2,3]])

[ 1 18 35 52]


In [10]:
d2_5 = np.arange(25,101,2).reshape(2,19)
print(d2_5)

[[25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61]
 [63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]]


In [12]:
d2_6 = np.arange(25,201,4).reshape(11,4)
print(d2_6)

[[ 25  29  33  37]
 [ 41  45  49  53]
 [ 57  61  65  69]
 [ 73  77  81  85]
 [ 89  93  97 101]
 [105 109 113 117]
 [121 125 129 133]
 [137 141 145 149]
 [153 157 161 165]
 [169 173 177 181]
 [185 189 193 197]]


In [24]:
l1 = d2_6[[2,3,4],[0,1,2]]
print(l1)

[57 77 97]


In [26]:
l2 = d2_6[[7,2,10,0],[1,2,0,2]]
print(l2)

[141  65 185  33]


In [29]:
l3 = [d2_6[2][0:2],d2_6[2][2:]]
print(l3)

[array([57, 61]), array([65, 69])]


In [89]:
d3_2=np.arange(25,201,4).reshape(2,11,2)
print(d3_2)

[[[ 25  29]
  [ 33  37]
  [ 41  45]
  [ 49  53]
  [ 57  61]
  [ 65  69]
  [ 73  77]
  [ 81  85]
  [ 89  93]
  [ 97 101]
  [105 109]]

 [[113 117]
  [121 125]
  [129 133]
  [137 141]
  [145 149]
  [153 157]
  [161 165]
  [169 173]
  [177 181]
  [185 189]
  [193 197]]]


In [90]:
print(d3_2[0][8][0])

89


In [91]:
d3_2.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [32]:
d3_3 = np.arange(1,65).reshape(4,4,4)
print(d3_3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]
  [41 42 43 44]
  [45 46 47 48]]

 [[49 50 51 52]
  [53 54 55 56]
  [57 58 59 60]
  [61 62 63 64]]]


In [33]:
print(d3_3[0,[0,1,2],[0,1,2]])

[ 1  6 11]


In [35]:
print(d3_3[[0,1],0,1])

[ 2 18]


In [37]:
print(d3_3[[0,2],[1],[1]])

[ 6 38]


In [2]:
d3_4 = np.arange(1,89).reshape(2,2,22)
print(d3_4)

[[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
  [23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]]

 [[45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66]
  [67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88]]]


In [4]:
print(d3_4[0][1][7:19])

[30 31 32 33 34 35 36 37 38 39 40 41]


In [6]:
d3_5 = np.arange(1,101).reshape(5,5,4)
print(d3_5)

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]
  [ 13  14  15  16]
  [ 17  18  19  20]]

 [[ 21  22  23  24]
  [ 25  26  27  28]
  [ 29  30  31  32]
  [ 33  34  35  36]
  [ 37  38  39  40]]

 [[ 41  42  43  44]
  [ 45  46  47  48]
  [ 49  50  51  52]
  [ 53  54  55  56]
  [ 57  58  59  60]]

 [[ 61  62  63  64]
  [ 65  66  67  68]
  [ 69  70  71  72]
  [ 73  74  75  76]
  [ 77  78  79  80]]

 [[ 81  82  83  84]
  [ 85  86  87  88]
  [ 89  90  91  92]
  [ 93  94  95  96]
  [ 97  98  99 100]]]


In [15]:
print(d3_5[[0,2],[1],[2,0]])
print(d3_5[[0,1,4],[0,1,0],[1,2,3]])
print(d3_5[[0,1,2,3,4],[2,2,2,2,3],[1,3,0,3,0]])
print(d3_5[[0,1,2,3],[1,1,2,2],[3,0,2,0]])
print(d3_5[[2],[0,1,2],[3]])

[ 7 45]
[ 2 27 84]
[10 32 49 72 93]
[ 8 25 51 69]
[44 48 52]


In [16]:
print(d3_5[[0,1,4],[0,1,0],[1:4]])


SyntaxError: invalid syntax (2426360244.py, line 1)

In [17]:
s1 = np.zeros(shape=(3,3),dtype=int)
print(s1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [18]:
s2 = np.ones(shape=(3,3),dtype=str)
print(s2)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [20]:
s3 = np.identity(6,dtype=int)
print(s3)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [22]:
s4 = np.eye(N=3,M=3,k=2)
print(s4)

[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
s4_1 = np.eye(N=3,M=3,k=1)
print(s4_1)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [24]:
s4_2 = np.eye(N=3,M=3)
print(s4_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
s5= np.empty(shape=(3,3),dtype=int)
print(s5)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [40]:
s6 = np.linspace(1,100,8,dtype=int)
print(s6)

[  1  15  29  43  57  71  85 100]


In [41]:
s7 = np.full(5,2,dtype=int)
print(s7)

[2 2 2 2 2]


In [42]:
s8 = np.full(shape=(3,4),fill_value=(5,7,8,17))
print(s8)

[[ 5  7  8 17]
 [ 5  7  8 17]
 [ 5  7  8 17]]


In [4]:
s8= np.full(shape=(3,4),fill_value=(1,2,3,4))
print(s8)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [47]:
s9 = np.random.random(12)
print(s9)

[0.68754171 0.45114594 0.05332113 0.88015098 0.35686981 0.5391826
 0.07328872 0.45588159 0.66690988 0.39110862 0.71661363 0.22477718]


In [27]:
s10 = np.random.randint(1,30,10)
print(s10)

[16 13 14 10 22 23 10 17 21 12]


In [7]:
s11 = np.random.choice(s10,size=4)
print(s11)

[20  5  7 21]


In [8]:
s12 = np.random.permutation(s10)
print(s12)

[14  7 21 27 10  5  9  6 20 11]


In [32]:
s13 = np.random.randint(1,30)
print(s13)

16


In [49]:
s14 = np.random.random()
print(s14)

0.5241136690971143


In [68]:
s15 = np.random.randint(1,1000,100)
p = np.random.randint(s15)
print(p)

[214 196 461 363 383 273 295 127 543  71 226  97 584 559  80  59  86  68
 715 220 668 220 407 106 476  63  92  21  84 156 412  11 720 320 148 487
  30 476  41 518 390 764 178 285 109  40  36 496 145  98   3 238  43 252
  24 336 213 864  43 440   1 267   0 399  16 218 283 804   0 307  89 504
 617 202  18 201 107 429  66  39 213 177 169   6 659 510 415  26 374 523
 597 771 574  25 201  20 193 154 447 291]


In [69]:
n = np.random.choice(p,size=25)
print(n)

[668  80 399 218  25 461  86 399 336  40 291 510 252  68 771  84 107 447
 169 156 213 154 307  24 273]


In [70]:
print(np.sum(n))

6538


In [74]:
l = [[1,2,3,],[4,5,6,],[7,8,9]]
type(l)
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [77]:
la = np.array(l)
print(la)
type(la)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [78]:
la.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [81]:
l2 = [[[1,2,3,],[4,5,6,]],[[7,8,9],[10,11,12]]]
la2 = np.array(l2)
print(la2)
print(la2.ndim)
la2.flags

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [83]:
la3 = la2.flatten()
print(la3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [85]:
la3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [86]:
la4 = la2.ravel()
print(la4)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [87]:
la3.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [ ]:
a1 = [1,2,3,4]


In [92]:
la2.flatten()
print(la2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [95]:
ar1 = np.random.randint(1,100,10)
print(ar1)
ar2 = np.random.randint(1,100,10)
print(ar2)

[11 58 77 77 34  8 15 65 48 51]
[16 77 30 96  1 81 53 82 60 31]


In [96]:
print(ar1+ar2)
print(ar1*ar2)
print(ar1-ar2)
print(ar1/ar2)

[ 27 135 107 173  35  89  68 147 108  82]
[ 176 4466 2310 7392   34  648  795 5330 2880 1581]
[ -5 -19  47 -19  33 -73 -38 -17 -12  20]
[ 0.6875      0.75324675  2.56666667  0.80208333 34.          0.09876543
  0.28301887  0.79268293  0.8         1.64516129]


In [97]:
ar3 = ar1.reshape(2,5)
ar4 = ar2.reshape(2,5)
print(ar3)
print(ar4)

[[11 58 77 77 34]
 [ 8 15 65 48 51]]
[[16 77 30 96  1]
 [81 53 82 60 31]]


In [98]:
print(ar3+ar4)
print(ar3*ar4)
print(ar3-ar4)
print(ar3/ar4)

[[ 27 135 107 173  35]
 [ 89  68 147 108  82]]
[[ 176 4466 2310 7392   34]
 [ 648  795 5330 2880 1581]]
[[ -5 -19  47 -19  33]
 [-73 -38 -17 -12  20]]
[[ 0.6875      0.75324675  2.56666667  0.80208333 34.        ]
 [ 0.09876543  0.28301887  0.79268293  0.8         1.64516129]]


In [101]:
sum1 = np.sum((ar3,ar4))
print(sum1)

971


In [102]:
sum2 = np.sum((ar3,ar4),axis=0)
print(sum2)

[[ 27 135 107 173  35]
 [ 89  68 147 108  82]]


In [104]:
sum3 = np.sum((ar3,ar4),axis=1)
print(sum3)

[[ 19  73 142 125  85]
 [ 97 130 112 156  32]]


In [108]:
mean1 = np.mean((ar3,ar4))
print(m1)

48.55


In [109]:
mean2 = np.mean((ar3,ar4),axis=0)
print(m2)

[[13.5 67.5 53.5 86.5 17.5]
 [44.5 34.  73.5 54.  41. ]]


In [110]:
mean3 = np.mean((ar3,ar4),axis=1)
print(m3)

[[ 9.5 36.5 71.  62.5 42.5]
 [48.5 65.  56.  78.  16. ]]


In [114]:
print(ar3)
print(ar4)

[[11 58 77 77 34]
 [ 8 15 65 48 51]]
[[16 77 30 96  1]
 [81 53 82 60 31]]


In [111]:
median1 = np.median((ar3,ar4))
print(median1)

52.0


In [112]:
median2 = np.median((ar3,ar4),axis=0)
print(median2)

[[13.5 67.5 53.5 86.5 17.5]
 [44.5 34.  73.5 54.  41. ]]


In [113]:
median3 = np.median((ar3,ar4),axis=1)
print(median3)

[[ 9.5 36.5 71.  62.5 42.5]
 [48.5 65.  56.  78.  16. ]]


In [120]:
ar5 = np.random.randint(1,100,12).reshape(2,2,3)
print(ar5)
ar6 = np.random.randint(1,100,12).reshape(2,2,3)
print(ar6)

[[[ 5 82 64]
  [48  7 69]]

 [[27  6  8]
  [76 95 46]]]
[[[39 29  2]
  [49 57 44]]

 [[42 77 65]
  [61 15 92]]]


In [121]:
sum4= np.sum((ar5,ar6))
print(sum4)

1105


In [125]:
sum5 = np.sum((ar5,ar6),axis=0)
print(sum5)

[[[ 44 111  66]
  [ 97  64 113]]

 [[ 69  83  73]
  [137 110 138]]]


In [126]:
sum6 = np.sum((ar5,ar6),axis=1)
print(sum6)

[[[ 32  88  72]
  [124 102 115]]

 [[ 81 106  67]
  [110  72 136]]]


In [127]:
sum7 = np.sum((ar5,ar6),axis=2)
print(sum7)

[[[ 53  89 133]
  [103 101  54]]

 [[ 88  86  46]
  [103  92 157]]]


In [128]:
for i in ar3:
    for j in i:
        print(j)

11
58
77
77
34
8
15
65
48
51


In [131]:

for i in ar5:
    for j in i:
        for k in j:
            print(k)

5
82
64
48
7
69
27
6
8
76
95
46


In [132]:
cnt = 0
for i in ar5:
    for j in i:
        for k in j:
            if (k%2==0):
                cnt +=1
print(cnt)

7


In [136]:
cnt = 0
for i in ar5:
    for j in i:
        for k in j:
            if (k%2==0 and k>48):
                cnt +=1
print(cnt)

3


In [134]:
print(ar5)

[[[ 5 82 64]
  [48  7 69]]

 [[27  6  8]
  [76 95 46]]]
